### PR TITLE
different updating implementation

### PR DESCRIPTION
**Pull request by TomW1605**
i don't expect you to accept this it was just the only way i could think of to compare the 2 files. i do think my implementation of the updating and a few other things is better but yours works so a change is not really necessary. i have done some code cleanup and style fixes that i sagest you do but up to you.

### CODE REVIEW

**Comment by OllisGit** [comment]
Hi TomW1605,
you cleaned and change a lot. First impression: looks good.

At the moment I have only one point:
The gcodeHook doesn't update the progress anymore, why? 
If you use only the progress hook you end up with "layer gaps":

First-Output: 1% 3/100
Second-Output: 2% 12/100

For models with less then 100 layer, everthings works fine, but if you have models with hundreds of layer and the display update is when percantage is change, you get "gaps"

Please explain.

**Comment by TomW1605** [comment]
the updateDisplay() function updates the display for both layer and progress and is called from both the progress hook and the gcode hook

**Comment by OllisGit** [comment]
sorry, I didn't saw that...hmm that works, because I had some trouble if I send gcode with `_printer.commands` in gcode-hook. Error was something like: ...receive duplicate commands...and the print stopped.

I will check your request in "real-live"!

**Comment by TomW1605** [comment]
odd i have't have that problem but i have only tested with the virtual printer plugin

**Comment by OllisGit** [comment]
I merged your PR, because a "real-live" test was successfull. I have no glue why this was not working in my implementation in the past.

You removed the progress-info from the navbar, because it is already in the statusbar...it's okay, but I need this info in the navbar. My tablet is so small that the statusbar is not shown.
Anyway, I will improve this later together with the "information-movement" to the statusbar.

I added two improvement: 
- When you select a model without layer-comments, the display shows the last evaluated layer-count.
- Everytime a model is selected the displays the total layercount instead of only 0%

Thanks alot for your support. I appreciate that.
Olli

**Comment by TomW1605** [comment]
sorry i forgot to mention i removed the percent display. i left the variable there and made another one that only shows layers. all u need to do it change line [99](https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/blob/e6285a6df33fff2e0dee051f380001549814c857/octoprint_DisplayLayerProgress/__init__.py#L99) by replacing `layerMessageNaveBar` with `progressMessageNavBar`.

i don't entirely understand your improvements. are they things that it was doing that you stopped or that it was not doing that you added?

**Pull request merged**
