### PR TITLE
Events optimization

### PR DESCRIPTION
**Pull request by gdombiak**
Before optimization
BEFORE

After optimization
AFTER

### CODE REVIEW

**Comment by OllisGit** [comment]
Hi @gdombiak ,

good timing: I just want to release a new version... my finger was over the release-button. 
Now I need to look into your PR ;-)

**Comment by OllisGit** [comment]
Wow, after optimization the plugin, it even didn't appear in the diagram...or did you attach the wrong screenshot?
I could not find the DLP-calls in the second screenshot.

**Comment by gdombiak** [comment]
That is the correct profiling image. :) DLP no longer appears in the radar of things that consume much CPU. It is mainly network stuff which is what is expected to find in an app like OctoPrint. User permissions check is there but it is insignificant % wise.

**Comment by OllisGit** [comment]
Implemented in Version 1.24.0.

Thx, again
Olli

**Pull request closed without merging**
